### ISSUE TITLE
version solving failed

### ISSUE THREAD

**Issue by kutear** [appwrite/sdk-for-flutter#17]
this library depended on the third libraries with lower version, it's hard to solved version  conflict.

and depneded so many library, compared with firebase(https://pub.dev/packages/firebase), it just depend on `http` libaray

**Comment by jr1221** [comment]
I have the same problem, where I require ffi 1 or above.  I believe a migration to null safe dependencies would increase the versions enough.

**Comment by lohanidamodar** [comment]
@kutear until we publish the null safe version of Flutter SDK, if you are using with Flutter 2.0, please use this
```
appwrite:
    git:
     url: https://github.com/appwrite/sdk-for-flutter
     ref: feat-null-safety-new
```
