### ISSUE TITLE
Realtime User Auth

### ISSUE THREAD

**Issue by rlee1990** [appwrite/sdk-for-flutter#27]
Using the branch here:
```
appwrite:
    git:
      url: https://github.com/appwrite/sdk-for-flutter
      ref: feat-realtime
```

I am trying to listen to auth states but I do not get any events at all.
Here is the code:

```
late RealtimeSubscription sub;

  void _incrementCounter() {
    setState(() {
      try {
        AppWrite.instance
            .login(email: 'rickeylee1129@gmail.com', password: '12345678');
      } on AppwriteException catch (e) {
        print(e.message);
      }
      _counter++;
    });
  }

  @override
  void initState() {
    print('Starting');
    sub = AppWrite.instance.realtime.subscribe(['accounts']);
    print('Got Sub');
    sub.stream.listen((event) {
      print(event);
      var data = json.decode(event);
      print(data);
    });
    super.initState();
  }
```
